"""empty message

Revision ID: 7eaa87295531
Revises: ce48359e4468
Create Date: 2021-06-24 20:31:35.909262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eaa87295531'
down_revision = 'ce48359e4468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venue_genres_Venue_fkey', 'venue_genres', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genres', 'Venue', ['Venue'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genres', type_='foreignkey')
    op.create_foreign_key('venue_genres_Venue_fkey', 'venue_genres', 'Artist', ['Venue'], ['id'])
    # ### end Alembic commands ###
